// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddUserApiUserAddPostData, AddUserApiUserAddPostErrors, AddUserApiUserAddPostResponses, DeleteUserApiUserDeletePostData, DeleteUserApiUserDeletePostErrors, DeleteUserApiUserDeletePostResponses, GetLoginUserApiUserGetLoginGetData, GetLoginUserApiUserGetLoginGetErrors, GetLoginUserApiUserGetLoginGetResponses, GetUserByIdApiUserGetGetData, GetUserByIdApiUserGetGetErrors, GetUserByIdApiUserGetGetResponses, HealthCheckApiHealthGetData, HealthCheckApiHealthGetResponses, ListUsersApiUserListPagePostData, ListUsersApiUserListPagePostErrors, ListUsersApiUserListPagePostResponses, LoginApiUserLoginPostData, LoginApiUserLoginPostErrors, LoginApiUserLoginPostResponses, LogoutApiUserLogoutPostData, LogoutApiUserLogoutPostErrors, LogoutApiUserLogoutPostResponses, RegisterApiUserRegisterPostData, RegisterApiUserRegisterPostErrors, RegisterApiUserRegisterPostResponses, UpdateUserApiUserUpdatePostData, UpdateUserApiUserUpdatePostErrors, UpdateUserApiUserUpdatePostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 */
export const healthCheckApiHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckApiHealthGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthCheckApiHealthGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/api/health',
        ...options
    });
};

/**
 * Register
 */
export const registerApiUserRegisterPost = <ThrowOnError extends boolean = false>(options: Options<RegisterApiUserRegisterPostData, ThrowOnError>) => {
    return (options.client ?? client).post<RegisterApiUserRegisterPostResponses, RegisterApiUserRegisterPostErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/user/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Login
 */
export const loginApiUserLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiUserLoginPostData, ThrowOnError>) => {
    return (options.client ?? client).post<LoginApiUserLoginPostResponses, LoginApiUserLoginPostErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/user/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Logout
 */
export const logoutApiUserLogoutPost = <ThrowOnError extends boolean = false>(options?: Options<LogoutApiUserLogoutPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<LogoutApiUserLogoutPostResponses, LogoutApiUserLogoutPostErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/user/logout',
        ...options
    });
};

/**
 * Get Login User
 */
export const getLoginUserApiUserGetLoginGet = <ThrowOnError extends boolean = false>(options?: Options<GetLoginUserApiUserGetLoginGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetLoginUserApiUserGetLoginGetResponses, GetLoginUserApiUserGetLoginGetErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/user/get/login',
        ...options
    });
};

/**
 * Get User By Id
 */
export const getUserByIdApiUserGetGet = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdApiUserGetGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetUserByIdApiUserGetGetResponses, GetUserByIdApiUserGetGetErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/user/get',
        ...options
    });
};

/**
 * List Users
 */
export const listUsersApiUserListPagePost = <ThrowOnError extends boolean = false>(options: Options<ListUsersApiUserListPagePostData, ThrowOnError>) => {
    return (options.client ?? client).post<ListUsersApiUserListPagePostResponses, ListUsersApiUserListPagePostErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/user/list/page',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Add User
 */
export const addUserApiUserAddPost = <ThrowOnError extends boolean = false>(options: Options<AddUserApiUserAddPostData, ThrowOnError>) => {
    return (options.client ?? client).post<AddUserApiUserAddPostResponses, AddUserApiUserAddPostErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/user/add',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Update User
 */
export const updateUserApiUserUpdatePost = <ThrowOnError extends boolean = false>(options: Options<UpdateUserApiUserUpdatePostData, ThrowOnError>) => {
    return (options.client ?? client).post<UpdateUserApiUserUpdatePostResponses, UpdateUserApiUserUpdatePostErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/user/update',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete User
 */
export const deleteUserApiUserDeletePost = <ThrowOnError extends boolean = false>(options: Options<DeleteUserApiUserDeletePostData, ThrowOnError>) => {
    return (options.client ?? client).post<DeleteUserApiUserDeletePostResponses, DeleteUserApiUserDeletePostErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/user/delete',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
