// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8567' | (string & {});
};

/**
 * BaseResponse[LoginUserVO]
 */
export type BaseResponseLoginUserVo = {
    /**
     * Code
     */
    code?: number;
    data?: LoginUserVo | null;
    /**
     * Message
     */
    message?: string;
};

/**
 * BaseResponse[UserVO]
 */
export type BaseResponseUserVo = {
    /**
     * Code
     */
    code?: number;
    data?: UserVo | null;
    /**
     * Message
     */
    message?: string;
};

/**
 * BaseResponse[bool]
 */
export type BaseResponseBool = {
    /**
     * Code
     */
    code?: number;
    /**
     * Data
     */
    data?: boolean | null;
    /**
     * Message
     */
    message?: string;
};

/**
 * BaseResponse[dict]
 */
export type BaseResponseDict = {
    /**
     * Code
     */
    code?: number;
    /**
     * Data
     */
    data?: {
        [key: string]: unknown;
    } | null;
    /**
     * Message
     */
    message?: string;
};

/**
 * BaseResponse[int]
 */
export type BaseResponseInt = {
    /**
     * Code
     */
    code?: number;
    /**
     * Data
     */
    data?: number | null;
    /**
     * Message
     */
    message?: string;
};

/**
 * BaseResponse[str]
 */
export type BaseResponseStr = {
    /**
     * Code
     */
    code?: number;
    /**
     * Data
     */
    data?: string | null;
    /**
     * Message
     */
    message?: string;
};

/**
 * DeleteRequest
 */
export type DeleteRequest = {
    /**
     * Id
     */
    id: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginUserVO
 */
export type LoginUserVo = {
    /**
     * Id
     */
    id: number;
    /**
     * Useraccount
     */
    userAccount: string;
    /**
     * Username
     */
    userName?: string | null;
    /**
     * Useravatar
     */
    userAvatar?: string | null;
    /**
     * Userprofile
     */
    userProfile?: string | null;
    /**
     * Userrole
     */
    userRole: string;
    /**
     * Viptime
     */
    vipTime?: string | null;
    /**
     * Createtime
     */
    createTime: string;
    /**
     * Updatetime
     */
    updateTime: string;
};

/**
 * UserAddRequest
 */
export type UserAddRequest = {
    /**
     * Useraccount
     */
    userAccount: string;
    /**
     * Userpassword
     */
    userPassword: string;
    /**
     * Username
     */
    userName?: string | null;
    /**
     * Useravatar
     */
    userAvatar?: string | null;
    /**
     * Userprofile
     */
    userProfile?: string | null;
    /**
     * Userrole
     */
    userRole?: string;
};

/**
 * UserLoginRequest
 */
export type UserLoginRequest = {
    /**
     * Useraccount
     */
    userAccount: string;
    /**
     * Userpassword
     */
    userPassword: string;
};

/**
 * UserQueryRequest
 */
export type UserQueryRequest = {
    /**
     * Current
     */
    current?: number;
    /**
     * Pagesize
     */
    pageSize?: number;
    /**
     * Sortfield
     */
    sortField?: string | null;
    /**
     * Sortorder
     */
    sortOrder?: string | null;
    /**
     * Id
     */
    id?: number | null;
    /**
     * Useraccount
     */
    userAccount?: string | null;
    /**
     * Username
     */
    userName?: string | null;
    /**
     * Userprofile
     */
    userProfile?: string | null;
    /**
     * Userrole
     */
    userRole?: string | null;
};

/**
 * UserRegisterRequest
 */
export type UserRegisterRequest = {
    /**
     * Useraccount
     */
    userAccount: string;
    /**
     * Userpassword
     */
    userPassword: string;
    /**
     * Checkpassword
     */
    checkPassword: string;
};

/**
 * UserUpdateRequest
 */
export type UserUpdateRequest = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    userName?: string | null;
    /**
     * Useravatar
     */
    userAvatar?: string | null;
    /**
     * Userprofile
     */
    userProfile?: string | null;
    /**
     * Userrole
     */
    userRole?: string | null;
};

/**
 * UserVO
 */
export type UserVo = {
    /**
     * Id
     */
    id: number;
    /**
     * Useraccount
     */
    userAccount: string;
    /**
     * Username
     */
    userName?: string | null;
    /**
     * Useravatar
     */
    userAvatar?: string | null;
    /**
     * Userprofile
     */
    userProfile?: string | null;
    /**
     * Userrole
     */
    userRole: string;
    /**
     * Viptime
     */
    vipTime?: string | null;
    /**
     * Createtime
     */
    createTime: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type HealthCheckApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseStr;
};

export type HealthCheckApiHealthGetResponse = HealthCheckApiHealthGetResponses[keyof HealthCheckApiHealthGetResponses];

export type RegisterApiUserRegisterPostData = {
    body: UserRegisterRequest;
    path?: never;
    query?: never;
    url: '/api/user/register';
};

export type RegisterApiUserRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiUserRegisterPostError = RegisterApiUserRegisterPostErrors[keyof RegisterApiUserRegisterPostErrors];

export type RegisterApiUserRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseInt;
};

export type RegisterApiUserRegisterPostResponse = RegisterApiUserRegisterPostResponses[keyof RegisterApiUserRegisterPostResponses];

export type LoginApiUserLoginPostData = {
    body: UserLoginRequest;
    path?: never;
    query?: never;
    url: '/api/user/login';
};

export type LoginApiUserLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiUserLoginPostError = LoginApiUserLoginPostErrors[keyof LoginApiUserLoginPostErrors];

export type LoginApiUserLoginPostResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseLoginUserVo;
};

export type LoginApiUserLoginPostResponse = LoginApiUserLoginPostResponses[keyof LoginApiUserLoginPostResponses];

export type LogoutApiUserLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/logout';
};

export type LogoutApiUserLogoutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutApiUserLogoutPostError = LogoutApiUserLogoutPostErrors[keyof LogoutApiUserLogoutPostErrors];

export type LogoutApiUserLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseBool;
};

export type LogoutApiUserLogoutPostResponse = LogoutApiUserLogoutPostResponses[keyof LogoutApiUserLogoutPostResponses];

export type GetLoginUserApiUserGetLoginGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/get/login';
};

export type GetLoginUserApiUserGetLoginGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLoginUserApiUserGetLoginGetError = GetLoginUserApiUserGetLoginGetErrors[keyof GetLoginUserApiUserGetLoginGetErrors];

export type GetLoginUserApiUserGetLoginGetResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseLoginUserVo;
};

export type GetLoginUserApiUserGetLoginGetResponse = GetLoginUserApiUserGetLoginGetResponses[keyof GetLoginUserApiUserGetLoginGetResponses];

export type GetUserByIdApiUserGetGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: number;
    };
    url: '/api/user/get';
};

export type GetUserByIdApiUserGetGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserByIdApiUserGetGetError = GetUserByIdApiUserGetGetErrors[keyof GetUserByIdApiUserGetGetErrors];

export type GetUserByIdApiUserGetGetResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseUserVo;
};

export type GetUserByIdApiUserGetGetResponse = GetUserByIdApiUserGetGetResponses[keyof GetUserByIdApiUserGetGetResponses];

export type ListUsersApiUserListPagePostData = {
    body: UserQueryRequest;
    path?: never;
    query?: never;
    url: '/api/user/list/page';
};

export type ListUsersApiUserListPagePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListUsersApiUserListPagePostError = ListUsersApiUserListPagePostErrors[keyof ListUsersApiUserListPagePostErrors];

export type ListUsersApiUserListPagePostResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseDict;
};

export type ListUsersApiUserListPagePostResponse = ListUsersApiUserListPagePostResponses[keyof ListUsersApiUserListPagePostResponses];

export type AddUserApiUserAddPostData = {
    body: UserAddRequest;
    path?: never;
    query?: never;
    url: '/api/user/add';
};

export type AddUserApiUserAddPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddUserApiUserAddPostError = AddUserApiUserAddPostErrors[keyof AddUserApiUserAddPostErrors];

export type AddUserApiUserAddPostResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseInt;
};

export type AddUserApiUserAddPostResponse = AddUserApiUserAddPostResponses[keyof AddUserApiUserAddPostResponses];

export type UpdateUserApiUserUpdatePostData = {
    body: UserUpdateRequest;
    path?: never;
    query?: never;
    url: '/api/user/update';
};

export type UpdateUserApiUserUpdatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiUserUpdatePostError = UpdateUserApiUserUpdatePostErrors[keyof UpdateUserApiUserUpdatePostErrors];

export type UpdateUserApiUserUpdatePostResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseBool;
};

export type UpdateUserApiUserUpdatePostResponse = UpdateUserApiUserUpdatePostResponses[keyof UpdateUserApiUserUpdatePostResponses];

export type DeleteUserApiUserDeletePostData = {
    body: DeleteRequest;
    path?: never;
    query?: never;
    url: '/api/user/delete';
};

export type DeleteUserApiUserDeletePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiUserDeletePostError = DeleteUserApiUserDeletePostErrors[keyof DeleteUserApiUserDeletePostErrors];

export type DeleteUserApiUserDeletePostResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseBool;
};

export type DeleteUserApiUserDeletePostResponse = DeleteUserApiUserDeletePostResponses[keyof DeleteUserApiUserDeletePostResponses];
